version: "3"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - "db"
  db:
    image: postgres
    ports:
      - "8001:5432"
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_PORT: 5432
      POSTGRES_DB: mydb